### ISSUE TITLE
Please provide a working sample on how to load and use g.js

### ISSUE THREAD

**Issue by rvnath** [nodebox/vg.js#2]
This set of files (g.js and its sub-folders) seems to use some sort of "require" specification with relative paths.  I tried creating a require js based AMD module and load this package.  In particular, I tried:
1. googled and added locally scoped require as suggested by some answers. No luck
2. Tried creating a package specification in require.config, but still didn't work.

Can you kindly provide me with a complete example of how to load and use this library.

**Comment by stebanos** [comment]
We currently use browserify to bundle all the source files and the dependencies in one big file.
Make sure you have node.js installed so you can do:
- npm install

to install browserify and the other dependencies.
You could then do:
- npm run browserify

This will create a build folder with a g.js inside of it. You can use this g.js file in your own projects.

**Comment by fdb** [comment]
Note that this is a temporary solution – we'll work on a process to distribute ready-made builds.

**Comment by rvnath** [comment]
OK, that works for me.
